### ISSUE TITLE
Reference to /opt/SWEAGLE

### ISSUE THREAD

**Issue by lrochette** [dimitris-sweagle/sweagle-ansible#2]
the file roles/sweagle/files/createService_v2.sh has a reference to /opt/SWEAGLE
It should be /opt/sweagle

all-install.yml also a reference but it's commented. I think it should be fix as well
same with install_appservers.yml

**Comment by dimitris-sweagle** [comment]
I corrected both issues you put below about /SWEAGLE folder hardcoded.
I change the comments and I put a shell command to dynamically calculate sweagle installation path from the component path argument (I would have preferred to put it as arg  instead of component but I wanted to reduce impact and so, keep same args as before for compatibility).
 
BTW, please note this has no impact on customer or POCs installation, because Relic is only used internally for performance monitoring.
